name: Build wheel

on:
  workflow_dispatch:
    inputs:
      llvm-branch:
        description: The LLVM branch to release from
        type: string
        required: true
      version:
        description: The version number to release
        type: string
        required: true
      python-version:
        description: The Python version to build the wheel for
        type: string
        required: true
      modify-existing-release:
        description: Whether the release already exists
        type: bool

jobs:
  build:
    name: Build dist files
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set version in pyproject.toml
        run: |
          sed -i 's/VERSION/"${{ inputs.version }}"/' pyproject.toml
          cat pyproject.toml

      - name: Clone LLVM
        uses: actions/checkout@v7
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: ${{ inputs.llvm-branch }}

      - name: Build wheel
        run: |
          pip install build
          CMAKE_BUILD_PARALLEL_LEVEL=8 SKBUILD_CMAKE_SOURCE_DIR=llvm-project/llvm python -m build --wheel --verbose .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  pypi:
    name: Push dist to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github_release:
    name: Create/update GitHub release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create new release
        if: ! inputs.modify-existing-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --title ${{ inputs.version }} ${{ inputs.version }} dist/*

      - name: Update existing release
        if: inputs.modify-existing-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload --clobber ${{ inputs.version }} dist/*
